version: 0.2
env:
  shell: bash
  parameter-store:
    DOCKERHUB_USERNAME: dockerUsername
    DOCKERHUB_PASSWORD: dockerPassword

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 804295906245.dkr.ecr.us-east-1.amazonaws.com
      - echo logging in docker hub
      - docker login -u="$DOCKERHUB_USERNAME" -p="$DOCKERHUB_PASSWORD"
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t demo .
      - docker tag demo:latest 804295906245.dkr.ecr.us-east-1.amazonaws.com/demo:latest  
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 804295906245.dkr.ecr.us-east-1.amazonaws.com/demo:latest
