version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/t5q8o1b3
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t dockerdemo .
      - docker tag dockerdemo:latest public.ecr.aws/t5q8o1b3/dockerdemo:latest     
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push public.ecr.aws/t5q8o1b3/dockerdemo:latest
